services:
  dbbackup:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dbbackup
    volumes:
      - ./public:/app/public
      - ./database:/app/database
      - ./databases:/app/databases
    env_file:
      - .env
    ports:
      - 4321:4321
    restart: always

volumes:
  dbbackup:
    driver: local
